# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 沈阳理工大学健康系统自动填报

on:
  schedule:
   - cron: 0 8 * * *
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Launch main.py
      env:
        STU_ID: ${{secrets.STU_ID}}
        STU_PWD: ${{secrets.STU_PWD}}
        STU_EMAIL: ${{secrets.STU_EMAIL}}
        EMAIL_USER: ${{secrets.EMAIL_USER}}
        EMAIL_PWD: ${{secrets.EMAIL_PWD}}
      run: |
        python main.py
